import {Types,ClientSession} from 'mongoose';import {connectDB} from '@/lib/db';import Party from '@/models/Party';import Product from '@/models/Product';import Transaction from '@/models/Transaction';import {TransactionInput} from '@/lib/validations/domain';
export class TransactionServiceError extends Error{code:string;details?:unknown;constructor(code:string,message:string,details?:unknown){super(message);this.code=code;this.details=details;}}
function assertFinite(n:number,name:string){if(!Number.isFinite(n)||n<0)throw new TransactionServiceError('INVALID_AMOUNT',`${name} must be a non-negative finite number`);}
export async function createTransaction(input:TransactionInput,userId:string,session?:ClientSession){if(!Types.ObjectId.isValid(userId))throw new TransactionServiceError('UNAUTHORIZED','Invalid user');assertFinite(input.amount,'Amount');assertFinite(input.quantity,'Quantity');if(!session)await connectDB();const own=!session;const s=session??await Transaction.startSession();const uid=new Types.ObjectId(userId);try{let result:any;const run=async()=>{
 if(input.partyId){if(!Types.ObjectId.isValid(input.partyId))throw new TransactionServiceError('INVALID_PARTY','Invalid party');const party=await Party.findOne({_id:new Types.ObjectId(input.partyId),userId:uid}).session(s);if(!party)throw new TransactionServiceError('NOT_FOUND','Party not found');}
 if(input.productId){if(!Types.ObjectId.isValid(input.productId))throw new TransactionServiceError('INVALID_PRODUCT','Invalid product');const product=await Product.findOne({_id:new Types.ObjectId(input.productId),userId:uid}).session(s);if(!product)throw new TransactionServiceError('NOT_FOUND','Product not found');}
 if(input.type==='DUE_GIVEN'||input.type==='DUE_RECEIVED'){if(!input.partyId)throw new TransactionServiceError('INVALID_PARTY','Party is required');if(input.amount<=0)throw new TransactionServiceError('INVALID_AMOUNT','Amount must be positive');const delta=input.type==='DUE_GIVEN'?input.amount:-input.amount;const updated=await Party.updateOne({_id:new Types.ObjectId(input.partyId),userId:uid},{$inc:{currentBalance:delta}},{session:s});if(updated.matchedCount!==1)throw new TransactionServiceError('NOT_FOUND','Party not found');}
 if(['STOCK_IN','STOCK_OUT','SALE'].includes(input.type)){if(!input.productId)throw new TransactionServiceError('INVALID_PRODUCT','Product is required');if(input.quantity<=0)throw new TransactionServiceError('INVALID_STOCK','Positive quantity is required');const p=await Product.findOne({_id:new Types.ObjectId(input.productId),userId:uid}).session(s);if(!p)throw new TransactionServiceError('NOT_FOUND','Product not found');const delta=input.type==='STOCK_IN'?input.quantity:-input.quantity;const next=p.stockQuantity+delta;if(next<0)throw new TransactionServiceError('INSUFFICIENT_STOCK',`Not enough stock. Available: ${p.stockQuantity}`);const set:any={stockQuantity:next};if(input.unitPrice!==undefined){if(input.type==='STOCK_IN')set.buyPrice=input.unitPrice;if(input.type==='SALE')set.sellPrice=input.unitPrice;}await Product.updateOne({_id:p._id,userId:uid},{$set:set},{session:s});}
 if(input.type==='EXPENSE'&&input.amount<=0)throw new TransactionServiceError('INVALID_AMOUNT','Expense amount must be positive');
 const [tx]=await Transaction.create([{userId:uid,partyId:input.partyId?new Types.ObjectId(input.partyId):undefined,productId:input.productId?new Types.ObjectId(input.productId):undefined,type:input.type,amount:input.amount,quantity:input.quantity,unitPrice:input.unitPrice,notes:input.notes,timestamp:input.timestamp||new Date()}],{session:s});result={id:String(tx._id),type:tx.type,amount:tx.amount,quantity:tx.quantity};};if(own)await s.withTransaction(run);else await run();return result;}finally{if(own)await s.endSession();}}
export async function reverseTransaction(id:string,userId:string,session?:ClientSession){if(!Types.ObjectId.isValid(id)||!Types.ObjectId.isValid(userId))throw new TransactionServiceError('INVALID_ID','Invalid id');if(!session)await connectDB();const own=!session;const s=session??await Transaction.startSession();const uid=new Types.ObjectId(userId);try{let result:any;const run=async()=>{const tx=await Transaction.findOne({_id:new Types.ObjectId(id),userId:uid}).session(s);if(!tx)throw new TransactionServiceError('NOT_FOUND','Transaction not found');if(tx.type==='DUE_GIVEN'||tx.type==='DUE_RECEIVED'){if(!tx.partyId)throw new TransactionServiceError('REVERSAL_BLOCKED','Party is missing');const delta=tx.type==='DUE_GIVEN'?-tx.amount:tx.amount;const r=await Party.updateOne({_id:tx.partyId,userId:uid},{$inc:{currentBalance:delta}},{session:s});if(r.matchedCount!==1)throw new TransactionServiceError('NOT_FOUND','Party not found');}if(['STOCK_IN','STOCK_OUT','SALE'].includes(tx.type)&&tx.productId){const product=await Product.findOne({_id:tx.productId,userId:uid}).session(s);if(!product)throw new TransactionServiceError('NOT_FOUND','Product not found');const delta=tx.type==='STOCK_IN'?-tx.quantity:tx.quantity;const next=product.stockQuantity+delta;if(next<0)throw new TransactionServiceError('REVERSAL_BLOCKED','Cannot reverse this stock entry because later movements already consumed the stock.');await Product.updateOne({_id:tx.productId,userId:uid},{$set:{stockQuantity:next}},{session:s});}await Transaction.deleteOne({_id:tx._id,userId:uid},{session:s});result={deletedId:String(tx._id)};};if(own)await s.withTransaction(run);else await run();return result;}finally{if(own)await s.endSession();}}
