'use client';
import {useRef,useState} from 'react';import {Mic,Loader2,Check,AlertCircle,Volume2,X,Send,ChevronRight} from 'lucide-react';import {AnimatePresence,motion} from 'framer-motion';

type Intent=Record<string,any>;type State='Idle'|'Listening'|'Processing'|'Success'|'Error';
function message(intent:Intent,result:any){if(intent.intent==='CREATE_PARTY')return `${result.name} নামে ${result.partyType==='SUPPLIER'?'সাপ্লায়ার':'কাস্টমার'} যোগ করা হয়েছে।`;if(intent.intent==='CREATE_PRODUCT')return `${result.name} পণ্যটি স্টকে যোগ করা হয়েছে। বর্তমান স্টক ${result.stock} ${result.unit}।`;if(intent.intent==='READ_BALANCE')return `${result.name} এর বর্তমান ব্যালেন্স ${Math.abs(result.balance)} টাকা।`;if(intent.intent==='UPDATE_STOCK')return `${result.name} এর স্টক আপডেট হয়েছে। বর্তমান স্টক ${result.stock} ${result.unit}।`;if(intent.transaction_type==='SALE')return 'বিক্রির হিসাব সংরক্ষণ করা হয়েছে।';if(intent.intent==='DELETE_ENTRY')return 'শেষ নির্ধারিত এন্ট্রি মুছে দেওয়া হয়েছে।';if(intent.transaction_type==='EXPENSE')return `${result.amount} টাকার খরচ সংরক্ষণ করা হয়েছে।`;if(intent.transaction_type==='DUE_GIVEN')return 'বাকির হিসাব যোগ করা হয়েছে।';if(intent.transaction_type==='DUE_RECEIVED')return 'জমার হিসাব সংরক্ষণ করা হয়েছে।';return 'হিসাব সফলভাবে সংরক্ষণ করা হয়েছে।';}
export default function VoiceControl(){const[state,setState]=useState<State>('Idle');const[text,setText]=useState('');const[error,setError]=useState('');const[pending,setPending]=useState<{intent:Intent;kind:'confirm'|'ambiguous';matches?:any[]}|null>(null);const latest=useRef('');const recognition=useRef<any>(null);
 const speak=(s:string)=>{if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(s);u.lang='bn-BD';u.rate=.95;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}};
 const execute=async(intent:Intent,t:string,confirmed=false)=>{setState('Processing');try{const r=await fetch('/api/voice-execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent,transcript:t,confirmed})});const d=await r.json();if(!r.ok||!d.ok){if(d.code==='AMBIGUOUS_ENTITY'||d.code==='DUPLICATE_ENTITY'){setPending({intent,kind:'ambiguous',matches:d.details?.matches||[]});return;}if(d.code==='CONFIRMATION_REQUIRED'){setPending({intent,kind:'confirm'});return;}throw new Error(d.error||'Execution failed');}setState('Success');setError('');const spoken=message(intent,d.result);speak(spoken);setTimeout(()=>setState('Idle'),1800);window.dispatchEvent(new Event('talikhata:refresh'));}catch(e:any){setState('Error');setError(e.message||'Execution failed');}};
 const process=async(t:string)=>{if(!t.trim())return;setState('Processing');try{const r=await fetch('/api/voice-parse',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({transcript:t})});const p=await r.json();if(!r.ok)throw new Error(p.error||'পার্সিং ব্যর্থ হয়েছে');if(p.intent==='READ_BALANCE'||p.intent==='LIST_ITEMS'){await execute(p,t);return;}if((p.amount&&p.amount>10000)||p.intent==='DELETE_ENTRY'||p.intent==='CREATE_PRODUCT'||p.intent==='CREATE_PARTY'){setPending({intent:p,kind:'confirm'});return;}await execute(p,t);}catch(e:any){setState('Error');setError(e.message||'ভয়েস প্রসেস করা যায়নি');}};
 const start=()=>{setError('');setText('');latest.current='';if(!('SpeechRecognition'in window||'webkitSpeechRecognition'in window)){setError('এই ব্রাউজারে voice recognition নেই। নিচের text box ব্যবহার করুন।');setState('Error');return;}const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;const r=new C();recognition.current=r;r.lang='bn-BD';r.interimResults=true;r.continuous=false;r.onstart=()=>setState('Listening');r.onresult=(e:any)=>{let out='';for(let i=0;i<e.results.length;i++)out+=e.results[i][0].transcript;latest.current=out;setText(out)};r.onerror=()=>{setState('Error');setError('ভয়েস ইনপুট নেওয়া যায়নি। Text command চেষ্টা করুন।')};r.onend=()=>{if(latest.current.trim())process(latest.current.trim())};r.start();};
 const confirm=()=>{const p=pending;if(!p)return;setPending(null);execute(p.intent,latest.current||text,true)};
 const choose=(m:any)=>{const p=pending;if(!p)return;setPending(null);execute({...p.intent,entity_name:m.name},latest.current||text)};
 const submitText=(e:React.FormEvent)=>{e.preventDefault();process(text)};
 return <><div className="fixed bottom-5 right-5 z-50 flex flex-col items-end gap-2"><AnimatePresence>{text&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="w-72 rounded-2xl border bg-white p-4 shadow-xl"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">Live transcript</span><button onClick={()=>setText('')}><X size={15}/></button></div><p className="mt-2 text-sm">{text}</p></motion.div>}</AnimatePresence><button onClick={start} disabled={state==='Listening'||state==='Processing'} className={`flex h-16 w-16 items-center justify-center rounded-full text-white shadow-2xl transition ${state==='Error'?'bg-red-600':state==='Success'?'bg-emerald-500':'bg-emerald-600 hover:bg-emerald-700'}`} aria-label="Voice command">{state==='Listening'?<motion.div animate={{scale:[1,1.25,1]}} transition={{repeat:Infinity,duration:.8}}><Mic/></motion.div>:state==='Processing'?<Loader2 className="animate-spin"/>:state==='Success'?<Check/>:state==='Error'?<AlertCircle/>:<Mic/>}</button><span className="rounded-full bg-white px-3 py-1 text-xs shadow">{state}</span>{error&&<div className="max-w-xs rounded-xl border border-red-100 bg-white p-3 text-xs text-red-600 shadow">{error}</div>}</div>
 <div className="fixed bottom-5 left-1/2 z-40 hidden w-[min(520px,calc(100%-140px))] -translate-x-1/2 md:block"><form onSubmit={submitText} className="flex gap-2 rounded-2xl border bg-white p-2 shadow-xl"><input value={text} onChange={e=>setText(e.target.value)} placeholder="অথবা লিখুন: রহিমের বাকি ৫০০ টাকা" className="min-w-0 flex-1 border-0 px-3 outline-none"/><button className="rounded-xl bg-slate-900 p-3 text-white"><Send size={17}/></button></form></div>
 <AnimatePresence>{pending&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/50 p-4"><motion.div initial={{scale:.96,y:10}} animate={{scale:1,y:0}} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">নিশ্চিত করুন</h2><button onClick={()=>setPending(null)}><X/></button></div><p className="mt-2 text-sm text-slate-500">{pending.kind==='ambiguous'?'একাধিক মিল পাওয়া গেছে। সঠিকটি নির্বাচন করুন।':'এই voice command চালানোর আগে নিশ্চিত করুন।'}</p>{pending.matches?.length? <div className="mt-4 space-y-2">{pending.matches.map((m:any)=><button key={m.id} onClick={()=>choose(m)} className="flex w-full items-center justify-between rounded-2xl border p-4 text-left hover:bg-emerald-50"><span><b>{m.name}</b><small className="block text-slate-500">{m.phone||''}{m.balance!==undefined?` • Balance ৳${m.balance}`:''}</small></span><ChevronRight size={18}/></button>)}</div>:null}<div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-semibold">Command</p><p className="mt-1">{text}</p></div><div className="mt-5 flex gap-3"><button onClick={()=>setPending(null)} className="btn-secondary flex-1">Cancel</button><button onClick={confirm} className="btn-primary flex-1">Confirm</button></div></motion.div></motion.div>}</AnimatePresence></>
}
